//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class reportCurve {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal reportCurve() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.reportCurve", typeof(reportCurve).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 相关系数R2= 的本地化字符串。
        /// </summary>
        internal static string coefficientR2 {
            get {
                return ResourceManager.GetString("coefficientR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑体 的本地化字符串。
        /// </summary>
        internal static string FontHei {
            get {
                return ResourceManager.GetString("FontHei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宋体 的本地化字符串。
        /// </summary>
        internal static string FontSong {
            get {
                return ResourceManager.GetString("FontSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 质控图 的本地化字符串。
        /// </summary>
        internal static string Qualitychart {
            get {
                return ResourceManager.GetString("Qualitychart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 质控值： 的本地化字符串。
        /// </summary>
        internal static string QualityValue {
            get {
                return ResourceManager.GetString("QualityValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相对 的本地化字符串。
        /// </summary>
        internal static string relatively {
            get {
                return ResourceManager.GetString("relatively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定标曲线方程及相关系数： 的本地化字符串。
        /// </summary>
        internal static string SClingCurve {
            get {
                return ResourceManager.GetString("SClingCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定标曲线报告 的本地化字符串。
        /// </summary>
        internal static string SClingReport {
            get {
                return ResourceManager.GetString("SClingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准 的本地化字符串。
        /// </summary>
        internal static string standard {
            get {
                return ResourceManager.GetString("standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准曲线坐标点： 的本地化字符串。
        /// </summary>
        internal static string Standardpoints {
            get {
                return ResourceManager.GetString("Standardpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计信息: 的本地化字符串。
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
    }
}
