//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioBaseCLIA.Resources.String {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NetCom3 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NetCom3() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BioBaseCLIA.Resources.String.NetCom3", typeof(NetCom3).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 正在中止线程 的本地化字符串。
        /// </summary>
        internal static string Abortthread {
            get {
                return ResourceManager.GetString("Abortthread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清洗模块清洗盘光电异常! 的本地化字符串。
        /// </summary>
        internal static string Cleanabnormal {
            get {
                return ResourceManager.GetString("Cleanabnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清洗模块垂直光电异常! 的本地化字符串。
        /// </summary>
        internal static string Cleanverticalabnormal {
            get {
                return ResourceManager.GetString("Cleanverticalabnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试系统通讯故障，实验将停止 的本地化字符串。
        /// </summary>
        internal static string communicationfail {
            get {
                return ResourceManager.GetString("communicationfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 理杯机模块理杯块光电开关异常! 的本地化字符串。
        /// </summary>
        internal static string Cupabnormal {
            get {
                return ResourceManager.GetString("Cupabnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断开连接！ 的本地化字符串。
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 理杯机模块抓空光电开关异常! 的本地化字符串。
        /// </summary>
        internal static string Emptyabnormal {
            get {
                return ResourceManager.GetString("Emptyabnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 理杯机模块抓手光电开关异常! 的本地化字符串。
        /// </summary>
        internal static string Gripperabnormal {
            get {
                return ResourceManager.GetString("Gripperabnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温育盘模块温育盘光电开关异常! 的本地化字符串。
        /// </summary>
        internal static string Incubateabnormal {
            get {
                return ResourceManager.GetString("Incubateabnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温育盘模块压杯光电开关异常! 的本地化字符串。
        /// </summary>
        internal static string Incubatepressureabnormal {
            get {
                return ResourceManager.GetString("Incubatepressureabnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温育盘模块垂直光电开关异常! 的本地化字符串。
        /// </summary>
        internal static string Incubateverticalabnormal {
            get {
                return ResourceManager.GetString("Incubateverticalabnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清洗模块计量泵光耦异常! 的本地化字符串。
        /// </summary>
        internal static string Measureabnormal {
            get {
                return ResourceManager.GetString("Measureabnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络连接不可用 的本地化字符串。
        /// </summary>
        internal static string Networkunavailable {
            get {
                return ResourceManager.GetString("Networkunavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加样模块柱塞泵光电开关异常! 的本地化字符串。
        /// </summary>
        internal static string Plungerabnormal {
            get {
                return ResourceManager.GetString("Plungerabnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口关闭！ 的本地化字符串。
        /// </summary>
        internal static string Portclosed {
            get {
                return ResourceManager.GetString("Portclosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清洗模块压杯光电异常! 的本地化字符串。
        /// </summary>
        internal static string Pressureabnormal {
            get {
                return ResourceManager.GetString("Pressureabnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加样模块试剂盘光电开关异常! 的本地化字符串。
        /// </summary>
        internal static string Reagentabnormal {
            get {
                return ResourceManager.GetString("Reagentabnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收数据异常: 的本地化字符串。
        /// </summary>
        internal static string Receiveexception {
            get {
                return ResourceManager.GetString("Receiveexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 理杯机模块旋转光电开关异常! 的本地化字符串。
        /// </summary>
        internal static string Rotatingphotoelectricabnormal {
            get {
                return ResourceManager.GetString("Rotatingphotoelectricabnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加样模块旋转臂光电开关异常! 的本地化字符串。
        /// </summary>
        internal static string Rotationabnormal {
            get {
                return ResourceManager.GetString("Rotationabnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加样模块样品盘光电开关异常! 的本地化字符串。
        /// </summary>
        internal static string Sampleabnormal {
            get {
                return ResourceManager.GetString("Sampleabnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息发送失败 的本地化字符串。
        /// </summary>
        internal static string Sendfailed {
            get {
                return ResourceManager.GetString("Sendfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 理杯机模块暂存盘光电开关异常! 的本地化字符串。
        /// </summary>
        internal static string Temporaryabnormal {
            get {
                return ResourceManager.GetString("Temporaryabnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加样模块垂直臂光电开关异常! 的本地化字符串。
        /// </summary>
        internal static string Verticalanomal {
            get {
                return ResourceManager.GetString("Verticalanomal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 理杯机模块垂直光电开关异常! 的本地化字符串。
        /// </summary>
        internal static string Verticalphotoelectricabnormal {
            get {
                return ResourceManager.GetString("Verticalphotoelectricabnormal", resourceCulture);
            }
        }
    }
}
