//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioBaseCLIA.Resources.String.LIS.HL7 {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HLObject {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HLObject() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BioBaseCLIA.Resources.String.LIS.HL7.HLObject", typeof(HLObject).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 字段的数据类型错误 的本地化字符串。
        /// </summary>
        internal static string DatatypeErr {
            get {
                return ResourceManager.GetString("DatatypeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件代号不支持 的本地化字符串。
        /// </summary>
        internal static string EventcodeNosupported {
            get {
                return ResourceManager.GetString("EventcodeNosupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一个段中丢失必须的字段 的本地化字符串。
        /// </summary>
        internal static string FieldMiss {
            get {
                return ResourceManager.GetString("FieldMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在重复的关键字 的本地化字符串。
        /// </summary>
        internal static string keywordrepeat {
            get {
                return ResourceManager.GetString("keywordrepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息类型不正确 的本地化字符串。
        /// </summary>
        internal static string MessageTypeErr {
            get {
                return ResourceManager.GetString("MessageTypeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询没有找到数据 的本地化字符串。
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 病人信息不存在 的本地化字符串。
        /// </summary>
        internal static string NoPatient {
            get {
                return ResourceManager.GetString("NoPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息中段的顺序不正确 的本地化字符串。
        /// </summary>
        internal static string OrderErr {
            get {
                return ResourceManager.GetString("OrderErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理ID不支持 的本地化字符串。
        /// </summary>
        internal static string Processidnosupported {
            get {
                return ResourceManager.GetString("Processidnosupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表值未找到 的本地化字符串。
        /// </summary>
        internal static string TableNoFount {
            get {
                return ResourceManager.GetString("TableNoFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事务在应用程序存储级不能执行 的本地化字符串。
        /// </summary>
        internal static string TransactionsNoExecute {
            get {
                return ResourceManager.GetString("TransactionsNoExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不明的应用程序内部其他错误 的本地化字符串。
        /// </summary>
        internal static string UnknownErr {
            get {
                return ResourceManager.GetString("UnknownErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本ID不支持 的本地化字符串。
        /// </summary>
        internal static string Versionidnosupported {
            get {
                return ResourceManager.GetString("Versionidnosupported", resourceCulture);
            }
        }
    }
}
